# Absenteeism
The Absenteeism dataset gives the data and reasons for employees being absent in a particular company Our job is to find the leading cause of abseentism among employees.

We will use a Logistic Regression model from ScikitLearn inorder to find the major contributor of the cause.
in this note book we will build a Logistic Regression model with the scaled preprocessed data.

# Creating a logistic regression to predict absenteeism

# Import the relevant libraries

In [1]:
# import the relevant libraries
import pandas as pd
import numpy as np

# Load the preprocessed data

In [2]:

# load the preprocessed CSV data
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

data_preprocessed.head()


Reason_1  Reason_2  Reason_3  Reason_4  Day of the week  Month Value  \
0         0         0         0         1                1            7   
1         0         0         0         0                1            7   
2         0         0         0         1                2            7   
3         1         0         0         0                3            7   
4         0         0         0         1                3            7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [3]:
# Create targets and inputs

# find the median of 'Absenteeism Time in Hours'
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

Create targets for our logistic regression, they have to be in categories and we must find a way to say if someone is 'being absent too much' or not
we wil take the median of the dataset as a cut-off line in this way the dataset will be balanced (there will be roughly equal number of 0s and 1s for the logistic regression)as balancing is a great problem for ML

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()


Reason_1  Reason_2  Reason_3  Reason_4  Day of the week  Month Value  \
0         0         0         0         1                1            7   
1         0         0         0         0                1            7   
2         0         0         0         1                2            7   
3         1         0         0         0                3            7   
4         0         0         0         1                3            7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [6]:
# check if dataset is balanced (what % of targets are 1s)(almost 50:50)
targets.sum() / targets.shape[0]

0.45571428571428574

In [7]:
# create a checkpoint by dropping the unnecessary variables
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the week',
                                            'Daily Work Load Average','Distance to Work'],axis=1)

In [8]:
data_with_targets is data_preprocessed

False

In [9]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [10]:
# Inputs for regression

data_with_targets.shape

(700, 12)

In [11]:
# Selects all rows and all columns until 14 (excluding)
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [12]:
# Create a variable that will contain the inputs (everything without the targets)
unscaled_inputs = data_with_targets.iloc[:,:-1]

# Normalizing the data

## Standardize the inputs
A very useful module we can use is StandardScaler it has much more capabilities than the straightforward 'preprocessing' method.
#### from sklearn.preprocessing import StandardScaler
We will create a variable that will contain the scaling information for this particular dataset
more about this on: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

In [13]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [14]:
# Fit the scaler
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [15]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [16]:
scaled_inputs.shape

(700, 11)

# Split the data into train & test and shuffling

### Import the relevant module

In [17]:
# import train_test_split so we can split our data into train and test
from sklearn.model_selection import train_test_split

## Splitting

In [18]:
train_test_split(scaled_inputs, targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          2.67996851, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976]]),
 array([[ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -

In [19]:
# declare 4 variables for the splitted data
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [20]:
# check the shape of the train inputs and targets
print (x_train.shape, y_train.shape)

(560, 11) (560,)


In [21]:
# check the shape of the test inputs and targets
print (x_test.shape, y_test.shape)

(140, 11) (140,)


## Logistic regression with sklearn

In [22]:
# import the LogReg model from sklearn
from sklearn.linear_model import LogisticRegression

# import the 'metrics' module, which includes important metrics we may want to use
from sklearn import metrics

### Training the model

In [23]:
# create a logistic regression object
reg = LogisticRegression()

### Fitting the data to LogReg model

In [24]:
# fit our train inputs
reg.fit(x_train,y_train)

LogisticRegression()

In [25]:
# assess the train accuracy of the model
reg.score(x_train,y_train)

0.7839285714285714

### Manually check the accuracy

In [26]:
# find the model outputs according to our model
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [27]:
# compare them with the targets
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [28]:
# ACTUALLY compare the two variables
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [29]:
# find out in how many instances we predicted correctly
np.sum((model_outputs==y_train))

439

In [30]:
# get the total number of instances
model_outputs.shape[0]

560

In [31]:
# calculate the accuracy of the model
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7839285714285714

### Finding the intercept and coefficients

In [32]:
# get the intercept (bias) of our model
reg.intercept_

array([-0.22415067])

In [33]:
# get the coefficients (weights) of our model
reg.coef_

array([[ 2.07060602,  0.33597918,  1.56203203,  1.31392372,  0.18468965,
         0.69080918, -0.19858992,  0.32509576, -0.12584894,  0.37082428,
        -0.32495752]])

In [34]:
# check what were the names of our columns
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [35]:
# save the names of the columns in an ad-hoc variable
feature_name = unscaled_inputs.columns.values

In [36]:
# use the coefficients from this table (they will be exported later and will be used in Tableau)
# transpose the model coefficients (model.coef_) and throws them into a df (a vertical organization, so that they can be
# multiplied by certain matrices later) 
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

# add the coefficient values to the summary table
summary_table['Coefficient'] = np.transpose(reg.coef_)

# display the summary table
summary_table

Feature name  Coefficient
0                 Reason_1     2.070606
1                 Reason_2     0.335979
2                 Reason_3     1.562032
3                 Reason_4     1.313924
4              Month Value     0.184690
5   Transportation Expense     0.690809
6                      Age    -0.198590
7          Body Mass Index     0.325096
8                Education    -0.125849
9                 Children     0.370824
10                    Pets    -0.324958

In [37]:
# do a little Python trick to move the intercept to the top of the summary table
# move all indices by 1
summary_table.index = summary_table.index + 1

# add the intercept at index 0
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

# sort the df by index
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -0.224151
1                 Reason_1     2.070606
2                 Reason_2     0.335979
3                 Reason_3     1.562032
4                 Reason_4     1.313924
5              Month Value     0.184690
6   Transportation Expense     0.690809
7                      Age    -0.198590
8          Body Mass Index     0.325096
9                Education    -0.125849
10                Children     0.370824
11                    Pets    -0.324958

## Interpreting the coefficients

In [38]:
# create a new Series called: 'Odds ratio' which will show the.. odds ratio of each feature
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [39]:
# display the df
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -0.224151    0.799195
1                 Reason_1     2.070606    7.929627
2                 Reason_2     0.335979    1.399310
3                 Reason_3     1.562032    4.768501
4                 Reason_4     1.313924    3.720744
5              Month Value     0.184690    1.202845
6   Transportation Expense     0.690809    1.995329
7                      Age    -0.198590    0.819886
8          Body Mass Index     0.325096    1.384163
9                Education    -0.125849    0.881748
10                Children     0.370824    1.448928
11                    Pets    -0.324958    0.722558

In [40]:
# sort the table according to odds ratio
# note that by default, the sort_values method sorts values by 'ascending'
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                 Reason_1     2.070606    7.929627
3                 Reason_3     1.562032    4.768501
4                 Reason_4     1.313924    3.720744
6   Transportation Expense     0.690809    1.995329
10                Children     0.370824    1.448928
2                 Reason_2     0.335979    1.399310
8          Body Mass Index     0.325096    1.384163
5              Month Value     0.184690    1.202845
9                Education    -0.125849    0.881748
7                      Age    -0.198590    0.819886
0                Intercept    -0.224151    0.799195
11                    Pets    -0.324958    0.722558

## Testing the model

In [41]:
# assess the test accuracy of the model
reg.score(x_test,y_test)

0.7357142857142858

In [42]:
# find the predicted probabilities of each class
# the first column shows the probability of a particular observation to be 0, while the second one - to be 1
predicted_proba = reg.predict_proba(x_test)

# let's check that out
predicted_proba

array([[0.70811655, 0.29188345],
       [0.5721039 , 0.4278961 ],
       [0.3987536 , 0.6012464 ],
       [0.78719503, 0.21280497],
       [0.0668946 , 0.9331054 ],
       [0.3111248 , 0.6888752 ],
       [0.28565469, 0.71434531],
       [0.08108162, 0.91891838],
       [0.79928258, 0.20071742],
       [0.74973079, 0.25026921],
       [0.46768065, 0.53231935],
       [0.18458351, 0.81541649],
       [0.04095243, 0.95904757],
       [0.7555815 , 0.2444185 ],
       [0.23782308, 0.76217692],
       [0.54134575, 0.45865425],
       [0.53349868, 0.46650132],
       [0.520355  , 0.479645  ],
       [0.40543527, 0.59456473],
       [0.02764621, 0.97235379],
       [0.7015122 , 0.2984878 ],
       [0.78719503, 0.21280497],
       [0.40550972, 0.59449028],
       [0.40550972, 0.59449028],
       [0.17426979, 0.82573021],
       [0.75364779, 0.24635221],
       [0.48844947, 0.51155053],
       [0.88051837, 0.11948163],
       [0.13089896, 0.86910104],
       [0.78719503, 0.21280497],
       [0.

In [43]:
predicted_proba.shape

(140, 2)

In [44]:
# select ONLY the probabilities referring to 1s
predicted_proba[:,1]

array([0.29188345, 0.4278961 , 0.6012464 , 0.21280497, 0.9331054 ,
       0.6888752 , 0.71434531, 0.91891838, 0.20071742, 0.25026921,
       0.53231935, 0.81541649, 0.95904757, 0.2444185 , 0.76217692,
       0.45865425, 0.46650132, 0.479645  , 0.59456473, 0.97235379,
       0.2984878 , 0.21280497, 0.59449028, 0.59449028, 0.82573021,
       0.24635221, 0.51155053, 0.11948163, 0.86910104, 0.21280497,
       0.37722038, 0.69563785, 0.71101679, 0.55846122, 0.21280497,
       0.56307123, 0.20931063, 0.80979261, 0.41300737, 0.6300506 ,
       0.20410533, 0.42159529, 0.22729926, 0.10466249, 0.85724567,
       0.65408304, 0.70636669, 0.29188345, 0.21168449, 0.19567294,
       0.56557265, 0.07759079, 0.6888752 , 0.26925275, 0.85966686,
       0.45388672, 0.93036835, 0.21790894, 0.08520077, 0.0894016 ,
       0.70577652, 0.67746261, 0.28724979, 0.86048417, 0.1899959 ,
       0.27057335, 0.01399431, 0.20931063, 0.81221789, 0.28543027,
       0.20931063, 0.06838131, 0.92866479, 0.47804084, 0.63876

The model came with a 73% accuracy score on test data and 78% on train data, which shows that our model is holding up and not overfitting.

From the above summary we can conclude that reasons 1,3 & 4 are the major contributors of absenteeism among employees of this organziation. With additional data and further tweaking of the model there is plenty of room for improvement in this case.

## Save the model

In [45]:
# import the relevant module
import pickle

In [46]:
# pickle the model file
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [47]:
# pickle the scaler file
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)